apps/exampleApp/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    #Para crud de categorias
    path('categorias/', views.CategoriaList.as_view(), name='categorias-list'),
    path('categorias/add/', views.CategoriaCreate.as_view(), name='categorias-add'),
    path('categorias/<pk>/', views.CategoriaDetail.as_view(),name="categorias-detail"),
    path('categorias/<pk>/update/',views.CategoriaUpdate.as_view(),name="categorias-update"),
    path('categorias/<pk>/delete/', views.CategoriaDelete.as_view(), name='categorias-delete'),
    #Para crud de SubCategoria
    path('subcategorias/',views.SubCategoriaList.as_view(),name='subcategorias-list'),
    path('subcategorias/add',views.SubCategoriaCreate2.as_view(),name='subcategorias-add'),
    path('subcategoria/<pk>',views.SubCategoriaDetail.as_view(),name="subcategorias-detail"),
    path('subcategorias/<pk>/delete/', views.SubCategoriaDelete.as_view(), name='subcategorias-delete'),
    path('subcategorias/<pk>/update/',views.SubCategoriaUpdate.as_view(),name="subcategorias-update"),
    #Para el crud de productos
    path('productos/',views.ProductoList.as_view(),name='productos-list'),
    path('productos/add/', views.ProductoCreate.as_view(), name='productos-add'),
    path('productos/<pk>/', views.ProductoDetail.as_view(),name="productos-detail"),
    path('productos/<pk>/update/',views.ProductoUpdate.as_view(),name="productos-update"),
     path('productos/<pk>/delete/', views.ProductoDelete.as_view(), name='productos-delete'),

]

example/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.exampleApp.urls', 'example'), namespace='example')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/exampleApp/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Categoria(models.Model):
    nombre = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        verbose_name=_('nombre'),
        help_text=_('Nombre de la categoría.')
    )

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = _('Categoria')
        verbose_name_plural = _('Categorías')
        ordering = ('nombre',)


class SubCategoria(models.Model):
    categoria = models.ForeignKey(
        blank=False,
        null=False,
        to=Categoria,
        on_delete=models.CASCADE,
        verbose_name=_('categoria'),
        help_text=_('Categoría principal.')
    )
    nombre = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        verbose_name=_('nombre'),
        help_text=_('Nombre de la sub categoría.')
    )

    def __str__(self):
        return '%s - %s' % (self.categoria, self.nombre)

    class Meta:
        verbose_name = _('SubCategoría')
        verbose_name_plural = _('SubCategorías')
        ordering = ('categoria', 'nombre')


class Producto(models.Model):
    subcategoria = models.ForeignKey(
        blank=False,
        null=False,
        to=SubCategoria,
        on_delete=models.CASCADE,
        verbose_name=_('subcategoría'),
        help_text=_('SubCategoría del producto.')
    )
    nombre = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        verbose_name=_('nombre'),
        help_text=_('Nombre del produto.')
    )
    descripion = models.TextField(
        max_length=150,
        blank=False,
        null=False,
        verbose_name=_('descripcion'),
        help_text=_('Descripción del producto.')
    )
    precio = models.DecimalField(
        blank=False,
        null=False,
        max_digits=10,
        decimal_places=2,
        verbose_name=_('precio'),
        help_text=_('Precio del producto.')
    )

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = _('Producto')
        verbose_name_plural = _('Productos')
        ordering = ('nombre',)

apps/exampleApp/forms.py
from django import forms

from . import models


class CategoriaForm(forms.ModelForm):

    class Meta:
        model = models.Categoria
        fields = ('nombre',)

CategoriaForm2 = forms.modelform_factory(
    model=models.Categoria,
    fields=('nombre',)
)
CategoriaFormset = forms.formset_factory(
    form=CategoriaForm2,
    extra=4,
    min_num=3,
    max_num=6
)

SubCategoriaFormset = forms.inlineformset_factory(
    parent_model=models.Categoria,
    model=models.SubCategoria,
    fields='__all__',
    extra=1,
    min_num=3,
    max_num=8,
)

ProductoFormset = forms.inlineformset_factory(
    parent_model=models.SubCategoria,
    model=models.Producto,
    fields='__all__',
    extra=1,
    min_num=2,
    max_num=8,
)

apps/exampleApp/views.py
from django.shortcuts import render

from django.views import generic
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin


from .models import *
from .forms import *
#Crud de SubCategorias
class SubCategoriaList(generic.ListView):
    model = SubCategoria
    context_object_name= 'subcategorias'


class SubCategoriaCreate2(generic.CreateView):
    model = SubCategoria
    fields = '__all__'
    success_url = reverse_lazy('example:subcategorias-list')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['productos'] = ProductoFormset(self.request.POST)
        else:
            data['productos'] = ProductoFormset()
        return data
    
    def form_valid(self, form):
        context = self.get_context_data()
        productos = context['productos']
        self.object = form.save()
        if productos.is_valid():
            productos.instance = self.object
            productos.save()
        return HttpResponseRedirect(self.get_success_url())


class SubCategoriaCreate(generic.CreateView):
    model = SubCategoria
    fields = '__all__'
    slug_field = 'nombre'
    success_url = reverse_lazy('example:subcategorias-list')


class SubCategoriaDetail(generic.DetailView):
    model = SubCategoria
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object:
            context['productos'] = Producto.objects.filter(subcategoria=self.object)
        print(context)
        return context


class SubCategoriaDelete(generic.DeleteView):
    model = SubCategoria
    success_url = reverse_lazy('example:subcategorias-list')


class SubCategoriaUpdate(generic.UpdateView):
    model = SubCategoria
    fields = ['categoria','nombre']
    success_url = reverse_lazy('example:subcategorias-list')


#Crud de Categorias
class CategoriaDetail(generic.DetailView):
    context_object_name = 'categoria'
    model = Categoria

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        if self.object:
            context['subcategorias'] = SubCategoria.objects.filter(categoria=self.object)      
        return context


class CategoriaUpdate(generic.UpdateView):
    model = Categoria
    fields = ['nombre']
    success_url = reverse_lazy('example:categorias-list')

    def get_context_data(self, **kwargs):
        if self.request.POST:
            kwargs['subcategorias'] = SubCategoriaFormset(self.request.POST)
        else:
            kwargs['subcategorias'] = SubCategoriaFormset(instance=self.object)
        kwargs.update()
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        context = self.get_context_data()
        subcategorias = context['subcategorias']
        self.object = form.save()
        if subcategorias.is_valid():
            subcategorias.instance = self.object
            subcategorias.save()
        return HttpResponseRedirect(self.get_success_url())


class CategoriaDelete(generic.DeleteView):
    model = Categoria
    success_url = reverse_lazy('example:categorias-list')


class CategoriaList(generic.ListView):
    model = Categoria
    context_object_name = 'categorias'


class CategoriaCreate(generic.CreateView):
    model = Categoria
    fields = '__all__'
    success_url = reverse_lazy('example:categorias-list')

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['subcategorias'] = SubCategoriaFormset(self.request.POST)
        else:
            data['subcategorias'] = SubCategoriaFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        subcategorias = context['subcategorias']
        self.object = form.save()
        if subcategorias.is_valid():
            subcategorias.instance = self.object
            subcategorias.save()
        return HttpResponseRedirect(self.get_success_url())


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name ='./index.html'


#Crud para productos
class ProductoList(generic.ListView):
    model = Producto


class ProductoCreate(generic.CreateView):
    model = Producto
    fields = '__all__'
    success_url = reverse_lazy('example:productos-list')


class ProductoDetail(generic.DetailView):    
    model = Producto


class ProductoUpdate(generic.UpdateView):
    model = Producto
    fields = ['subcategoria','nombre','descripion','precio']
    success_url = reverse_lazy('example:productos-list')


class ProductoDelete(generic.DeleteView):
    model = Producto
    success_url = reverse_lazy('example:productos-list')

templates/exampleapp/categoria_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

templates/exampleapp/categoria_detail copy.html
<h1>{{ subcategoria.nombre }}</h1>

templates/exampleapp/categoria_detail.html
<h1>{{ categoria.nombre }}</h1>
<ul>
{% for subcategoria in subcategorias %}
<li>{{subcategoria.nombre }}</li>
{% empty %}
<li>No hay ni mergas </li>
{% endfor %}
</ul>

templates/exampleapp/categoria_form.html
{% extends '../base.html' %}
{% block content %}
{% if object %}
<h2>Update Categoria</h2>
<form action="{% url 'example:categorias-update' object.pk %}" method="POST">
{% else %}
<h2>Nueva Categoria</h2>
<form action="{% url 'example:categorias-add' %}" method="POST">
{% endif %}
  {% csrf_token %}
  {{ form.as_p }}
  <h2>SUBCATEGORIAS</h2>
  {{ subcategorias.management_form }}
  <div id="container">
    {% for form in subcategorias %}
      <div class="form">
        {{form}}
      </div>
    {% endfor %}
  </div>
  <button type="button" id="btnAddForm" onclick="addForm('subcategoria')">Añadir</button>
  <h2>OCULTO</h2>
  <div class="hidden">
    {{ subcategorias.empty_form }}
  </div>
  <button type="submit">Guardar</button>
</form>
{% endblock %}

templates/exampleapp/categoria_list.html
{% extends '../base.html' %}
{% block content %}
  <h2>Categorías</h2>
  <a href="{% url 'example:categorias-add' %}">Añadir</a>
  <ul>
    {% for categoria in categorias %}
      <li>
        <a href="{% url 'example:categorias-detail' categoria.pk %}">
          {{ categoria.nombre }}
        </a>
        <a href="{% url 'example:categorias-update' categoria.pk %}">
          Editar
        </a>
        <a href="{% url 'example:categorias-delete' categoria.pk %}">
          Eliminar
        </a>
      </li>
    {% empty %}
      <p>No hay categorías</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/exampleapp/producto_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

templates/exampleapp/producto_detail.html
{% extends '../base.html'%}
{% block content%}
<h1>Detalle de Producto </h1>

<p>Nombre: <b>{{ producto.nombre }}</b></p>
<p>SubCategoria: <b>{{ producto.subcategoria }}</b></p>
<p>Descripcion: <b>{{ producto.descripion }}</b></p>
<p>precio: <b>{{ producto.precio }}</b></p>

{% endblock %}

templates/exampleapp/producto_form.html
{% extends '../base.html' %}
{% block content %}
{% if object %}
<h2>Update Producto</h2>
<form action="{% url 'example:productos-update' object.pk %}" method="POST">
  {% else %}
  <h2>Nueva Producto</h2>
  <form action="{% url 'example:productos-add' %}" method="POST">
    {% endif %}
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
  </form>
  {% endblock %}

templates/exampleapp/producto_list.html
{% extends '../base.html' %}
{% block content %}
  <h2>Productos</h2>
  <a href="{% url 'example:productos-add' %}">Añadir</a>
  <ul>
    {% for producto in object_list %}
      <li>
        <a href="{% url 'example:productos-detail' producto.pk %}">
          {{ producto.nombre }}
        </a>
        <a href="{% url 'example:productos-update' producto.pk %}">
          Editar
        </a>
        <a href="{% url 'example:productos-delete' producto.pk %}">
          Eliminar
        </a>
      </li>
    {% empty %}
      <p>No Productos</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/exampleapp/subcategoria_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

templates/exampleapp/subcategoria_detail.html
{% extends '../base.html'%}
{% block content%}
<h1>Detalle de subcategoria </h1>
<p>Nombre: <b>{{ subcategoria.nombre }}</b></p>
<span>Productos involucrados:</span>

<ul>
    {% for producto in productos %}
    <li>{{producto.nombre }}</li>
    {% empty %}
    <li>No hay ni mergas </li>
    {% endfor %}
</ul>
{% endblock %}

templates/exampleapp/subcategoria_form.html
{% extends '../base.html' %}
{% block content %}
{% if object %}
<h2>Update SubCategoria</h2>
<form action="{% url 'example:subcategorias-update' object.pk %}" method="POST">
  {% else %}
  <h2>Nueva SubCategoria</h2>
  <form action="{% url 'example:subcategorias-add' %}" method="POST">
    {% endif %}
    {% csrf_token %}
    {{ form.as_p }}

    <h2>Productos</h2>
    {{productos.management_form}}
    <div id="container">
      {% for form in productos %}
      <div class="form">
        {{form}}
        <br>
      </div>
      {% endfor %}
    </div>
    <button type="button" id="btnAddForm" onclick="addForm('producto')">Añadir</button>
    <h2>OCULTO</h2>
    <div class="hidden">
      {{productos.empty_form}}
    </div>
    <button type="submit">Guardar</button>
  </form>
  {% endblock %}

templates/exampleapp/subcategoria_list.html
{% extends '../base.html' %}
{% block content %}
<h2>SubCategorias</h2>
<a href="{% url 'example:subcategorias-add' %}">Añadir</a>
<ul>
  {% for subcategoria in subcategorias %}
  <li>
    <a href="{% url 'example:subcategorias-detail' subcategoria.pk %}">
      {{ subcategoria.nombre }}
    </a>
    <a href="{% url 'example:subcategorias-update' subcategoria.pk %}">
      Editar
     </a>
    <a href="{% url 'example:subcategorias-delete' subcategoria.pk %}">
     Eliminar
    </a>
  </li>
  {% empty %}
  <p>No hay subcategorías</p>
  {% endfor %}
</ul>
{% endblock %}