apps/exampleApp/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
    #Para crud de categorias
    path('categorias/', views.CategoriaList.as_view(), name='categorias-list'),
    path('categorias/add/', views.CategoriaCreate.as_view(), name='categorias-add'),
    path('categorias/<pk>/', views.CategoriaDetail.as_view(),name="categorias-detail"),
    path('categorias/<pk>/update/',views.CategoriaUpdate.as_view(),name="categorias-update"),
    path('categorias/<pk>/delete/', views.CategoriaDelete.as_view(), name='categorias-delete'),
    #Para crud de SubCategoria
    path('subcategorias/',views.SubCategoriaList.as_view(),name='subcategorias-list'),
    path('subcategorias/add',views.SubCategoriaCreate2.as_view(),name='subcategorias-add'),
    path('subcategoria/<pk>',views.SubCategoriaDetail.as_view(),name="subcategorias-detail"),
    path('subcategorias/<pk>/delete/', views.SubCategoriaDelete.as_view(), name='subcategorias-delete'),
    path('subcategorias/<pk>/update/',views.SubCategoriaUpdate.as_view(),name="subcategorias-update"),
    #Para el crud de productos
    path('productos/',views.ProductoList.as_view(),name='productos-list'),
    path('productos/add/', views.ProductoCreate.as_view(), name='productos-add'),
    path('productos/<pk>/', views.ProductoDetail.as_view(),name="productos-detail"),
    path('productos/<pk>/update/',views.ProductoUpdate.as_view(),name="productos-update"),
     path('productos/<pk>/delete/', views.ProductoDelete.as_view(), name='productos-delete'),

]

example/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.exampleApp.urls', 'example'), namespace='example')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ object_list.Meta.model.verbose_name }}</title>
</head>
<body>
  <ul>
    <li><a href="{% url 'example:categorias-list' %}">Categorías</a></li>
    <li><a href="{% url 'example:subcategorias-list' %}">SubCategorías</a></li>
    <li><a href="{% url 'example:productos-list' %}">Productos</a></li>
  </ul>
  {% block content %}
    
  {% endblock %}
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Inicio</title>
</head>
<body>
  <h1>¡Hola, mundo!</h1>

  {{ csrf_token }}
</body>
</html>